# Generated by Django 5.1.2 on 2024-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartGhrWali", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="purchased_on",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="usage",
            name="used_on",
            field=models.DateTimeField(),
        ),
    ]
