# Generated by Django 5.1.2 on 2024-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartGhrWali", "0002_alter_purchase_purchased_on_alter_usage_used_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="unit",
            field=models.CharField(default="kilogram", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
