# Generated by Django 5.1.2 on 2024-10-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartGhrWali", "0003_category_unit_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
