# Generated by Django 5.1.2 on 2024-10-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartGhrWali", "0004_item_expiry_date_alter_purchase_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
