# Generated by Django 5.1.2 on 2024-10-24 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartGhrWali", "0005_alter_item_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="min_quantity",
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchased_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usage",
            name="used_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
