# Generated by Django 5.1.2 on 2024-10-25 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SmartGhrWali",
            "0006_alter_item_min_quantity_alter_purchase_purchased_on_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="curr_quantity",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="min_quantity",
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="quantity",
            field=models.DecimalField(decimal_places=5, default=0.01, max_digits=10),
        ),
        migrations.AlterField(
            model_name="usage",
            name="used_quantity",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("user", "name")},
        ),
    ]
